version: 0.0
os: linux
files:
  - source: /
    destination: /new_chatapp
permissions:
  - object: /new_chatapp
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/cleanInstance.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restartServices.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/restartNginx.sh
      timeout: 300
      runas: root
